---
- name: Configure DB server
  hosts: db
  become: yes
  vars:
    login_host: 18.208.182.68
  vars_prompt:
    - name: mysql_root_password
      prompt: "Please enter the MySQL root password:"
      private: no

  tasks:
    - name: Download MySQL Yum repository RPM
      ansible.builtin.get_url:
        url: https://dev.mysql.com/get/mysql80-community-release-el7-6.noarch.rpm
        dest: /tmp/mysql80-community-release-el7-6.noarch.rpm

    - name: Install MySQL Yum repository
      ansible.builtin.yum:
        name: /tmp/mysql80-community-release-el7-6.noarch.rpm
        state: present

    - name: Install MySQL Server
      ansible.builtin.yum:
        name: mysql-server
        state: latest

    - name: Start and Enable MySQL server
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Install Python dependencies for MySQL
      ansible.builtin.pip:
        name:
          - PyMySQL
          - cryptography

    - name: Retrieve temporary MySQL root password
      ansible.builtin.shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
      register: mysql_temp_password
      changed_when: false

    - name: Reset MySQL root password
